### ISSUE TITLE
Why Ruby?

### ISSUE THREAD

**Issue by EricSB** [DarthFubuMVC/fubucore#103]
Given this code base is C# based, why in the world is ruby required to restore nuget packages and run unit tests??

**Comment by chester89** [comment]
May be because both fake and paket are relatively new - if I understand correctly, Fubu projects started in 2010 or earlier. Albacore was available at the time

**Comment by jeremydmiller** [comment]
Fubu used rake from the very beginning dating back to about '09ish. At the time - and I'd argue still - Rake was the easiest Make-like tool to use. 

@EricSB Dude, this is a very old codebase that isn't terribly active and there is no single choice of build tooling in the .Net world that won't make a majority of .Net developers complain about it.

**Comment by EricSB** [comment]
LOL Fair enough response Jeremy.
